### ISSUE TITLE
no title

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Blank#1]
![20170116_110302](https://cloud.githubusercontent.com/assets/15638605/21977223/f5cd9096-dbdd-11e6-8d07-fde9b9b656d3.jpg)

@MichaelTunnell Possible security issue or false positive. Never ever happened before. Download attempt on clean install.

**Comment by cinnamoner** [comment]
*Paranoid* is my default mode. Just tried the download the LTS. Same has happened. Says Win64:Vitro.

**Comment by cinnamoner** [comment]
![20170116_115856](https://cloud.githubusercontent.com/assets/15638605/21978476/7481931a-dbe3-11e6-98c8-6742ad51ed94.jpg)
It's not entirely relevant but it hasn't happened there. Darn.

**Comment by cinnamoner** [comment]
Look at the timestamps. It's for real. I'm not saying the images aren't clean.

**Comment by cinnamoner** [comment]
@feren Look into it, if you care. Thanks.

**Comment by cinnamoner** [comment]
![20170116_122941](https://cloud.githubusercontent.com/assets/15638605/21979470/aa0a8a38-dbe7-11e6-9bd9-d360d282ee76.jpg)
Again.

**Comment by cinnamoner** [comment]
![20170116_130654](https://cloud.githubusercontent.com/assets/15638605/21980823/4a0013b4-dbed-11e6-9174-0b7337fdbdcc.jpg)

Man in the middle? Don't know yet.

**Comment by cinnamoner** [comment]
@BigDaddyonTech Maybe just some crazy heuristics but I'm still concerned. The anticrap is configured as usually but that's irrelevant as well, I guess. The Peppermint download went through but the Neon ones failed.

**Comment by cinnamoner** [comment]
Have used the download file button as well mirror links. It's the same.

**Comment by cinnamoner** [comment]
I'll do further analysis.

**Comment by cinnamoner** [comment]
![20170116_134247](https://cloud.githubusercontent.com/assets/15638605/21981807/de83a146-dbf1-11e6-9252-246f1417af86.jpg)

One mirror out of many. This is pretty irrelevant as well. Might have DNS poisoning. Hahaha! Ain't funny at all.

**Comment by cinnamoner** [comment]
Remember. Before my first attempt to download Neon, the system had been fresh install as in everything and the apps from master DVD (clean).

**Comment by cinnamoner** [comment]
Oh, it's windows alright. Please don't hold that against me :)

**Comment by cinnamoner** [comment]
@feren I gather you're using Avast as well. What does yours say? Yeah tweak it up to the maximum. It's crap but the AOS plugin is okay if configured correctly. The joys of closed source crap.

**Comment by cinnamoner** [comment]
Michael, I'm trying to figure it out. Please be gentle, okay? It's for the greater good. Nothing personal.

**Comment by cinnamoner** [comment]
Going to be blanked out again soon ... okay?

**Comment by cinnamoner** [comment]
Let's try something else for a change.

**Comment by cinnamoner** [comment]
![20170116_150815](https://cloud.githubusercontent.com/assets/15638605/21984251/c60e03a2-dbfd-11e6-94af-873d9006a93c.jpg)

I feel miserable. Maui just went through without issues. I want Neon, damn it.

**Comment by cinnamoner** [comment]
Somthing ain't right. Opinionate! Oh, the December 29 had gone through just fine.

**Comment by feren** [comment]
@cinnamoner Try another anti-virus like MalwareBytes and see what it finds it to be...
(It may just be reported that because of that incident from a while ago, like they did the malicious Mint ISO)

**Comment by MichaelTunnell** [comment]
My bet is that Avast is wrong or you have a different type of infection.

Scanning the same mirrors via VirusTotal shows that neither have issues.

![screenshot_20170116_142716](https://cloud.githubusercontent.com/assets/1056731/21998445/79ffc318-dbfa-11e6-85fd-71b96a1a5d0e.png)
![screenshot_20170116_142901](https://cloud.githubusercontent.com/assets/1056731/21998446/7a04115c-dbfa-11e6-9906-bfbc9454825e.png)

**Comment by cinnamoner** [comment]
Seems the problem has been around for quite some time. There are reports in conjunction with other distros as well. Talking bout vitro in conjunction with avast. But ever since I've been downloading images from neon it's for the first time avast cuts the download. @feren I'm using Malwarebytes as an on demand scanner, not live. Two live untivruses running at the same time is absolutely not recommend. Also, Malwarebytes is designed for other forms of malware.

**Comment by cinnamoner** [comment]
Anyhow the damn thing is in the casper/vmlinuz. There's been compliant concerning the docker images as well (neon). Some Manjaro spins have been reported with the same issue.
***
No problem with Maui and Peppermint.
***
I'd say it's a false positive but I'm not all that sure. It's annoying when one is forced to disable the shields just to download Neon.

**Comment by cinnamoner** [comment]
@MichaellTunnell I think it's Avast's heuristic engine but I still feel uncomfortable with the whole thing.

**Comment by cinnamoner** [comment]
I'll scan the previous iso. Let's see what happens. At the time of it's download, avast hadn't detected anything.

**Comment by MichaelTunnell** [comment]
To ease your mind I did tests myself of the ISOs and the casper/vmlinuz files, and they are all fine from all mirrors you mentioned being flagged.

The sha256sums of the ISOs on acc.umu.se, lip6.fr, and kde.org are all exactly the same.

I went a step farther by downloading the ISOs from each of those mirrors to extract the casper/vmlinuz files and test those directly. Unsurprisingly, they all are the same files and all sha256sums are exactly the same.

So if it were infected then all mirrors should be infected and not just some of them because they are all exact copies of the same files. (the purpose of mirrors)

Conclusion: Avast is a piece of crap and flagged something incorrectly making you think something is wrong when in fact, nothing is wrong.

-----

Why would a Neon ISO have a Windows virus in the first place? The point of an ISO is typically to replace Windows entirely so what would be the point of infecting something that is likely to be removed anyway?

**Comment by cinnamoner** [comment]
@MichaelTunnell Thank you, Michael. Feel so much better now. I'm dumping Windows and Avast and all the paranoia that goes with that crap.

**Comment by cinnamoner** [comment]
Thread closed. Obliteration due soon. If someone else wants to add further comments, please do it now.

**Comment by cinnamoner** [comment]
@MichaelTunnell I shall switch all members of my family to Linux. To Neon, to be more precise. But it'll take a while. 
***
What is your overall option on Bitdefender? I know you don't care anymore about Windows stuff. But please humour me once more.
***
Just switched to Bitdefender and it hasn't reported anything wrong in conjunction with the Neon images.
***
I'm waiting for an answer. I wanna delete the repo asap. And switch to Telegram for chatting. Git is for development indeed. That would be all.

**Comment by cinnamoner** [comment]
![20170118_151746](https://cloud.githubusercontent.com/assets/15638605/22066057/c4b1d6fe-dd93-11e6-903f-d6a0f5bf07aa.jpg)
![20170118_151951](https://cloud.githubusercontent.com/assets/15638605/22066067/cfc9c36c-dd93-11e6-806b-210b21dbaa9f.jpg)
User 2016.12.29

***
![20170118_152207](https://cloud.githubusercontent.com/assets/15638605/22066117/23991bc8-dd94-11e6-9050-5868641ead51.jpg)
![20170118_152527](https://cloud.githubusercontent.com/assets/15638605/22066136/37f7508a-dd94-11e6-8c50-22196ca01d7b.jpg)
User 2017.01.16

@jriddle I understand those are false positives. Why is it happening? Consider those who are downloading from Windows and also have Avast (crapware) installed. Quite a crowd and some really want Neon for a daily driver. By the way, Neon is a light year ahead of anything. I simply love it. Please read the whole thread. Thank you.

**Comment by cinnamoner** [comment]
@MichaelTunnell Feel free to jump in. False Windows positives can still be damaging. It's a paradox.

**Comment by cinnamoner** [comment]
@BigDaddyonTech Long time no talk. I want this sorted out so I can delete it asap.

**Comment by cinnamoner** [comment]
My point is: Whenever Avast cuts the download, that might be deterring for some. Which is rather unfortunate cause lots of people blindly trust Avast (crapware). I've even wondered whether they do it on purpose.

**Comment by cinnamoner** [comment]
@feren Replicate the damn thing.

**Comment by feren** [comment]
@cinnamoner This is why I use Linux, you don't need Antiviruses if you're smart like me and don't have superuser running all the dang time

**Comment by cinnamoner** [comment]
@feren So you basically have no opinion on what causes Avast detect those false positives in Neon.

**Comment by cinnamoner** [comment]
I do understand a Windows virus/malware can't affect Linux. What if one accidentally crosscotaminates an ecosystem?

**Comment by cinnamoner** [comment]
LET me put it simply: what has changed in vmlinuz so dramatically to trigger a false positive detection. Please look @feren upstream more attentively. If you care, of course.

**Comment by cinnamoner** [comment]
Something must have changed. The "clean" vmlinuz and the "bad" were scanned with the same engine. The engine hasn't changed. The file has.

**Comment by cinnamoner** [comment]
... and that change triggered the false positive detection.

**Comment by cinnamoner** [comment]
... Or Avast is doing it on purpose.

**Comment by cinnamoner** [comment]
JUST submitted the vmlinuz and vmlinuz.efi to Avast for revaluation.

**Comment by cinnamoner** [comment]
![20170118_200433](https://cloud.githubusercontent.com/assets/15638605/22076648/9fe915f0-ddb9-11e6-8471-9d943bc0a19b.jpg)
Terribly sorry for the bad/twisted/upside-down pictures but beauty wasn't my concern. Thank you all.

**Comment by cinnamoner** [comment]
@jriddell Would be glad to hear from you on this issue. Thanks. Neon rules!

**Comment by cinnamoner** [comment]
@feren Quite disappointed for not having shown much interest.

**Comment by cinnamoner** [comment]
@bluedxca93 What do YOU think of it?

**Comment by cinnamoner** [comment]
Just verified my email. Avast say (an automated re; hahaha) they are only humans but will analyse the files. A human will contact me as well, they say. Looking forward to it causes it's not normal for an antivirus to block a Neon image from downloading with a massage popping up and saying they have found Win64:vitro in vmlinuz and vmlinuz.efi.
***
And of course, those files (extracted them with 7zip) are also interpreted in the exact same way on Virustotal by Avast. As shown above. So let's hope for the best. Would be nice if more people would participate to settle the issue with Avast. Right, @feren @MichaelTunnell @BigDaddyonTech @Elbullazul?

**Comment by bluedxca93** [comment]
that is a kernel at @cinnamoner.
it might run a specific linux that is a huge dangerous attack against
the windows or something else running on your computer.

**Comment by MichaelTunnell** [comment]
> This is why I use Linux, you don't need Antiviruses if you're smart like me and don't have superuser running all the dang time

You can just use Linux the way it was setup by default and not need an anti-virus. Not having superuser is the default state of most distros. In fact, Ubuntu doesn't even create a root user at all by default.

> LET me put it simply: what has changed in vmlinuz so dramatically to trigger a false positive detection?

Nothing. I think you are looking at the wrong end of the issue. Instead of wondering what changed in Neon to trigger a false positive, maybe it's what changed in Avast to all of the sudden trigger one.

> Something must have changed. The "clean" vmlinuz and the "bad" were scanned with the same engine. 

Anti-virus engines change every day with new definitions and database updates.

What about the files changed? I tested the same files you are referring to and they all had the same sha256sum as the original ISO so just testing the original file is enough but when I went further and tested them individually they were all fine.

Where *exactly* did you get the ISO/files that were triggering the false positive?

> Would be nice if more people would participate to settle the issue with Avast.

Avast is erroring with a false positive. It does that all the time, just like all of the other free anti-virus programs.

Your impatience is rather irritating to be honest, a family member of mine was in the hospital today and yet you are being condescending for my lack of commenting. Nice.

**Comment by cinnamoner** [comment]
@MichaelTunnell I'm not condescending in the slightest. I'm sorry for the medical problem. My grandfather is undergoing surgery in a couple of days. Sorry if I've irritated you. That wasn't my intention. The engine is in continuous transformation, true. The way I'm seeing it you haven't read the thread patiently and with the analytical granularity I was expecting. Sorry I have disturbed you. Won't happen again. That would be all. End of story.

**Comment by cinnamoner** [comment]
Man, I thought I was speaking English.

**Comment by cinnamoner** [comment]
@feren Please do me a last favour and go to the Neon webpage and screenshoot the md5, SHA1 and SHA256 for the latest User and User LTS images. Post the screenshots righ here. Remember: post but don't edit the posts.

**Comment by cinnamoner** [comment]
Update: A human from Avast says the files were sent to analysis.

**Comment by feren** [comment]
@MichaelTunnell Give your family member that's in hospital my good luck buddy, I hope he doesn't face the same fate Jamie Green did (Neiio)...

**Comment by cinnamoner** [comment]
@feren What is that all about? I'm not insensitive but ...

**Comment by feren** [comment]
@cinnamoner Do you want to know what happened to Neiio?

**Comment by cinnamoner** [comment]
@feren Since you're around, my I ask you for that favour again?

**Comment by feren** [comment]
@cinnamoner Which one?

**Comment by cinnamoner** [comment]
There's no reason to believe the cases are similar or even comparable.

**Comment by feren** [comment]
@cinnamoner I don't want to scare or be cynical to Micheal, but...

_...we have to be ready in case Nature does anything to him/her, after all, no one was ready for my dad to die of cancer out of the blue that fateful November 19th..._

**Comment by cinnamoner** [comment]
@feren I'm kindly asking you to go to the Neon site and screenshoot the MD5, SHA1 and SHA256 for the latest User and User LTS. Please post the shots but don't edit the posts afterwards. Thank you.

**Comment by feren** [comment]
User:
![screenshot from 2017-01-19 16-57-56](https://cloud.githubusercontent.com/assets/11057934/22116471/805a085c-de68-11e6-9eb8-f864e1e288b4.png)

**Comment by feren** [comment]
Oops, wrong view, hang on

**Comment by feren** [comment]
shasum for User:
![screenshot from 2017-01-19 16-59-23](https://cloud.githubusercontent.com/assets/11057934/22116539/ae37afb8-de68-11e6-88df-932da97867aa.png)

**Comment by cinnamoner** [comment]
@feren I'm as aware of what you have just posted as a human can possibly be. I hope it's nothing serious in this case. I know about pain as well. A lot.

**Comment by feren** [comment]
shasum for User LTS:
![screenshot from 2017-01-19 17-00-15](https://cloud.githubusercontent.com/assets/11057934/22116566/ca9edb54-de68-11e6-8dec-b9bbcd6b3a86.png)

**Comment by cinnamoner** [comment]
@feren I'd rather have it like the last time, remember?

**Comment by feren** [comment]
@cinnamoner I don't think I can get it like last time anymore

**Comment by cinnamoner** [comment]
@feren Why?

**Comment by cinnamoner** [comment]
@feren Go page > Shoot the whole screen > Post

**Comment by feren** [comment]
Oh, now it shows it for User LTS: *sigh*
![screenshot from 2017-01-19 17-18-32](https://cloud.githubusercontent.com/assets/11057934/22117291/5958128c-de6b-11e6-98f0-5067606930c0.png)

**Comment by feren** [comment]
@cinnamoner How curious, it doesn't have anything for Non-LTS:
http://files.kde.org/neon/images/neon-useredition/current/neon-useredition-20170119-1018-amd64.iso.mirrorlist

**Comment by cinnamoner** [comment]
@feren Yeah they uploaded it recently. The sums will show up shortly. Might take several hours though. Thanks.

**Comment by cinnamoner** [comment]
@feren So, should I switch to Open DNS?

**Comment by feren** [comment]
@cinnamoner Yeah, you probably should

**Comment by cinnamoner** [comment]
I got a notification from Avast. They said the files were false positives and the situation would remedy after update. So I updated and attempted to download again. Avast cut the download again. But the image had been updated again. My guess is Avast's heuristics can't handle those files properly. Haven't excluded the possibility I had been targeted by an attacker. Something is fishy. Dear attacker, I assure you there's no meat for you. The systems I'm using are testmachines. I'm also using a number of gateways to connect. You can't get into the mainframe but you can alway try. Also, it's rather unfortunate Neon doesn't have secure servers. I'll sorted out. I've got time. If it takes a whole year, then so be it. Neon is only a tinny fraction of all the projects I'm interested in. Hahaha!   😄😄😄
